<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Sviter.aspx.cs" Inherits="WebApplication1.Sviter" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#CC9966" BorderStyle="None" BorderWidth="1px" CellPadding="4" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" ShowFooter="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="SvitId"  Height="231px" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" OnRowCancelingEdit="GridView1_RowCancelingEdit1">
            <Columns>
                <asp:TemplateField HeaderText="Operations" ShowHeader="False">
                    <FooterTemplate>
                        <asp:LinkButton ID="LinkButton1" runat="server" OnClick="LinkButton3_Click1">Insert</asp:LinkButton>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="SvitId" InsertVisible="False" SortExpression="SvitId">
                    <EditItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("SvitId") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Eval("SvitId") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Svit" SortExpression="Svit">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Svit") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
                    </FooterTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Svit") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
            <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
            <RowStyle BackColor="White" ForeColor="#330099" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
            <SortedAscendingCellStyle BackColor="#FEFCEB" />
            <SortedAscendingHeaderStyle BackColor="#AF0101" />
            <SortedDescendingCellStyle BackColor="#F6F0C0" />
            <%--<SortedDescendingHeaderStyle BackColor="#7E0000"--%> 
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:BSB notarkivConnectionString2 %>" DeleteCommand="DELETE FROM [Svitar] WHERE [SvitId] = @SvitId AND [Svit] = @Svit" InsertCommand="INSERT INTO [Svitar] ([Svit]) VALUES (@Svit)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Svitar]" UpdateCommand="UPDATE [Svitar] SET [Svit] = @Svit WHERE [SvitId] = @SvitId AND [Svit] = @Svit">
        <DeleteParameters>
            <asp:Parameter Name="SvitId" Type="Int32" />
            <asp:Parameter Name="Svit" Type="String" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="Svit" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="Svit" Type="String" />
            <asp:Parameter Name="SvitId" Type="Int32" />
            <asp:Parameter Name="Svit" Type="String" />
        </UpdateParameters>
        </asp:SqlDataSource>

        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Låtar" />
        <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Kompositörer" />
        <asp:Button ID="Button3" runat="server" OnClick="Button3_Click" Text="Visa allt" />
    </form>
</body>
</html>
